### ISSUE TITLE
Update metadata only (no package) =>Error: EISDIR: illegal operation on a directory, read

### ISSUE THREAD

**Issue by tesar-tech** [microsoft/windows-dev-center-vsts-extension#89]
I am trying to update just the metedata for my app. Since `packagePath` is optional, this should work:

```yml
steps:
- task: store-publish@0
  inputs:
    serviceEndpoint: 'NaWinDevCenter'
    appId: '9PH5NNZ5BXFQ'
    metadataUpdateMethod: 'JsonMetadata'
    metadataPath: '$(system.defaultworkingdirectory)\NoApp\Store\appMetadata' 
    updateImages: true
    force: true 
    skipPolling: true
```

It throws `##[error]Unhandled: EISDIR: illegal operation on a directory, read` . This error is already discussed here https://github.com/microsoft/windows-dev-center-vsts-extension/issues/33 and after turning on the debug mode I found this:

`##[debug]Adding package path d:/a/1/s to zip as 0_s`

So the issue is probably caused by `d:/a/1/s` - **it is not a file**.

But what are my options here, if I don't want to add the package ???
