### ISSUE TITLE
Mandatory update flag is not reset after a release

### ISSUE THREAD

**Issue by radujipa** [microsoft/windows-dev-center-vsts-extension#97]
I have recently noticed that the mandatory update flag in Partner Center does not get reset after such a release was previously made.

![image](https://user-images.githubusercontent.com/3577547/107963200-c1fd0580-6f9f-11eb-8857-6988a02a925a.png)

My CD pipeline uses the following template for making releases to the Store:

```
# template.yml

parameters:
- name: environment
  type: string
  values:
  - 'ProductionPreview'
  - 'Production'
- name: appId
  type: string
- name: mandatoryUpdate  # Always true for ProductionPreview.
  type: boolean
  default: false

jobs:
- deployment: ReleaseToMicrosoftStore
  displayName: '${{parameters.environment}} Release to Microsoft Store'
  environment: '${{parameters.environment}}'
  strategy:
    runOnce:
      deploy:
        steps:
        - ${{if eq(parameters.environment, 'ProductionPreview')}}:
          - task: store-flight@0
            displayName: 'Deploy release candidate to package flight'
            continueOnError: true
            inputs:
              serviceEndpoint: 'Windows Partner Center'
              appId: '${{parameters.appId}}'
              flightName: 'Release Candidate (Kano Testers)'
              packagePath: '$(Pipeline.Workspace)/**/!(Test)*.*upload'
              force: true
              skipPolling: false
              deletePackages: true
              numberOfPackagesToKeep: '0'
              isMandatoryUpdate: true
              mandatoryUpdateDifferHours: '2'

        - ${{if eq(parameters.environment, 'Production')}}:
          - task: store-publish@0
            displayName: 'Deploy to public submission'
            continueOnError: true
            inputs:
              serviceEndpoint: 'Windows Partner Center'
              appId: '${{parameters.appId}}'
              packagePath: '$(Pipeline.Workspace)/**/!(Test)*.*upload'
              force: true
              skipPolling: false
              deletePackages: true
              numberOfPackagesToKeep: '0'
              ${{if eq(parameters.mandatoryUpdate, true)}}:
                isMandatoryUpdate: true
                mandatoryUpdateDifferHours: '2'
```

The CD pipeline itself has a `Mandatory Update` flag that can be ticked when running it manually. This gets passed on to the template and then to the store-flight/publish tasks. I've checked the pipeline logs and the task reports that the flag is being set off with the expanded pipeline showing that the last 2 lines above are not present.

#### Expected behaviour:
1. Release to Production (mandatory is false) : Partner Center submission Mandatory Update is not ticked.
2. Release to Production (mandatory is true) : Partner Center submission Mandatory Update is ticked.
3. Release to Production (mandatory is false) : Partner Center submission Mandatory Update **is not ticked.**

#### Actual behaviour:
1. Release to Production (mandatory is false) : Partner Center submission Mandatory Update is not ticked.
2. Release to Production (mandatory is true) : Partner Center submission Mandatory Update is ticked.
3. Release to Production (mandatory is false) : Partner Center submission Mandatory Update **is ticked.**
